version: '3.8'

services:
  db:
    image: postgres:15
    container_name: marketplace_db
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: marketplace
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: marketplace_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=marketplace;Username=marketplace;Password=secret123
    ports:
      - "5000:8080"
    restart: always

volumes:
  pgdata:
